BASE_URL = 'https://qa-scooter.praktikum-services.ru'
CREATE_COURIER = '/api/v1/courier'
LOGIN_COURIER = '/api/v1/courier/login'
DELET_COURIER = '/api/v1/courier/:id'
CREATE_ORDER = '/api/v1/orders'
LIST_ORDERS = '/api/v1/orders'
